### ISSUE TITLE
submit cubelyr to CRAN before submitting dplyr 0.9

### ISSUE THREAD

**Issue by edzer** [hadley/cubelyr#1]
Package `stars` dynamically imports `as.tbl_cube` from `dplyr`, but that will no longer work with the github `dplyr` version. It would be good to have this package on CRAN before `dplyr` 0.9 is going to be submitted, so that `stars` can be modified in time, or to let me know what to do otherwise.

**Comment by hadley** [comment]
Yes, it will be.

**Comment by edzer** [comment]
Great, thanks!
